CREATE DATABASE IF NOT EXISTS 4WINS;
USE 4WINS;
CREATE TABLE IF NOT EXISTS games(ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, player_id varchar(255), value double);
 
CREATE USER IF NOT EXISTS 'fourwins_read'@'%' IDENTIFIED BY 'fourwinsread';
CREATE USER IF NOT EXISTS 'fourwins_write'@'%' IDENTIFIED BY 'fourwinswrite';

GRANT SELECT ON 4WINS.* TO 'fourwins_read'@'%';
GRANT ALL PRIVILEGES ON 4WINS.* TO 'fourwins_write'@'%';

FLUSH PRIVILEGES; 

