CREATE DATABASE IF NOT EXISTS 4WINS;
CREATE TABLE IF NOT EXISTS games(ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, player_id VARCHAR(255), value DOUBLE);
CREATE USER fourwins_read IDENTIFIED BY "fourwinsread";
GRANT SELECT ON 4WINS.games TO fourwins_read;
